<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-SEE9OFQ" failures="1" tests="3" name="com.iween.testcase.TCCP_10" time="501.906" errors="0" timestamp="2025-08-20T23:00:41 IST" skipped="2">
  <testcase classname="com.iween.testcase.TCCP_10" name="myTest" time="159.585">
    <failure message="Validation failed: route/name/price mismatch." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Validation failed: route/name/price mismatch.
at org.testng.Assert.fail(Assert.java:111)
at com.skytraveller.pageObjects.PaymentGateWayPage.validatePayMentPage(PaymentGateWayPage.java:239)
at com.iween.testcase.TCCP_10.myTest(TCCP_10.java:258)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- myTest -->
  <testcase classname="com.iween.testcase.TCCP_10" name="myTest" time="160.808">
    <skipped/>
  </testcase> <!-- myTest -->
  <testcase classname="com.iween.testcase.TCCP_10" name="myTest" time="181.513">
    <skipped/>
  </testcase> <!-- myTest -->
</testsuite> <!-- com.iween.testcase.TCCP_10 -->
